---
abstract: 'REST interface for Nessus 6.0'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Nessus-REST
no_index:
  directory:
    - t
    - inc
requires:
  JSON: '0'
  LWP::UserAgent: '0'
resources:
  repository: git://github.com/guillomovitch/Net-Nessus-REST
version: 0.1
